filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /var/log/covid_cases/output.txt

  json.keys_under_root: true
  json.add_error_key: true
  json.overwrite_keys: true

processors:
  # - timestamp:
  #     field: reported_date
  #     timezone: 'America/Toronto'
  #     layouts:
  #       - '2020-01-01T00:00:00-04:00'
  # - drop_fields:
  #     fields: [reported_date]

#  - add_cloud_metadata: ~
#  - add_docker_metadata: ~

output.elasticsearch:
  hosts: '${ELASTICSEARCH_HOSTS:elasticsearch:9200}'
  username: '${ELASTICSEARCH_USERNAME:}'
  password: '${ELASTICSEARCH_PASSWORD:}'
